config/routes.rb
Rails.application.routes.draw do
  get 'rentals/new'
  get 'rentals/edit'
  get 'rentals/show'
  get 'rentals/index'

  get 'employees/new'
  get 'employees/edit'
  get 'employees/update'
  get 'employees/delete'
  get 'employees/show'
  get 'employees/index'

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'
  
  get 'static_pages/contact'

  get 'static_pages/register' 

  get 'static_pages/login'

  get 'static_page/logout'

  resources :employees
  resources :rentals

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
    validates :name, presence: true
end

app/models/rental.rb
class Rental < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
    def index
        render html: 'Hello world'
    end
end


    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
        @books = Book.all
    end
    def new
        @book = Book.new
    end
    def create
        @book = Book.new(book_params)
            if @book.save
                redirect_to books_path, 
                notice: "Book was created successfully"
            else 
                render :new
        end
    end
private 
  def book_params
    params.require(:book).permit :title, :connet, :author
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end
  def show 
    @employee = Employee.find_by id: params[:id]
  end
  def new
    @employee = Employee.new
  end

  def edit
    @employee = Employee.find_by id: params[:id]
  end
  def create
    
      em = Employee.new(employee_params)
      if em.save
      redirect_to employees_path
      else 
        render :new
      end
  end

  def update 
      @employee = Employee.find_by id: params[:id]
      if @employee.update(employee_params)
          redirect_to @employee,
          notice: "employee was updated successfully"
      else 
          render :index
     end
  end

  def delete
      if @employee.delete
          redirect_to employees_path, notice: "employee was deleted successfully"
      else
          render :index
     end
  end

private 

  def set_employee
     @employee = Employee.find_by id:params[:id]
  end
  def employee_params
     params.require(:employee).permit :name, :email , :password, :password_confirm
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
    def index
        @rentals = Rental.all
    end

    def show 
        @rental = Rental.find_by id: params[:id]
    end

    def new
        @rental = Rental.new
    end

    def create
        
        em = Rental.new(rental_params)
        if em.save
          redirect_to rentals_path
        else 
            render :new
        end
    end
private 
    def set_rental
        @rental = Rental.find_by id:params[:id]
    end
    def rental_params
     params.require(:rental).permit :name, :size , :price, :color, :amount
    end
    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
  def register
  end
  
  def login
  end

  def logout
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def setting_title title
    # if "#{title}".empty?
    #   my_title = "beautiful | My pages"
      # binding.pry
      title = "INSAL" if title.empty?
    # else 
      my_title = "#{title} | My pages"
  end
  def change_name
    name = "Ten toi la: Tien Animal ahihi :)"
    if current_page?(:controller => "static_pages", :action => "help")
      result = ""
      name.split("").reverse.each do |i|
        result = result + "#{i}"
      end
      return result
    elsif current_page?(:controller => "static_pages", :action => "about") 
      return name
    end
  end
end
# end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for book do |form| %>
    <div><%= form.label :title, value: "Title" %><div>
    <div><%= form.text_field :title %><div>
    <div><%= form.label :content, value: "Content" %><div>
    <div><%= form.text_area :content %><div>
    <div><%= form.label :author, value: "Author" %><div>
    <div><%= form.text_field :author %><div>
    <div><%= form.submit %><div>
<% end %>

app/views/books/index.html.erb
<ul>
  <% @books.each do |book| %>
    <li><%= book.id %></li>
    <li><%= book.title %></li>
    <li><%= book.content %></li>
    <li><%= book.author %></li>
  <% end %>
</ul>
<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render "form", book: @book %>
<%= link_to "Back", books_path %>

app/views/employees/_form.html.erb
<%= form_for employee do |f| %>
    <div class="form-group">
        <label for="name">Name:</label>
        <input name="name" class="form-control" id="name" />
    </div>
    <div class="form-group">
        <label for="email">Email:</label>
        <input type="email" name="email" class="form-control" id="email" />
    </div>
    <div class="form-group">
        <label for="password">Password:</label>
        <input type="password" name="password" class="form-control" id="password" />
    </div>
    <div class="form-group">
        <label for="password">Email:</label>
        <input type="password" name="password_confirm" class="form-control" id="password_confirm" />
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
    <% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>
<%= render 'form', employee: @employee %>
    <%= link_to 'Show', @employee %>
        <%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th>Password Confirm</th>
            <th>Action</th>
        </tr>
    </thead>
    <%= link_to  "new  ", new_employee_path %>
        <tbody>
            <% @employees.each do |employee| %>
                <tr>
                    <td>
                        <%= employee.name %>
                    </td>
                    <td>
                        <%= employee.email %>
                    </td>
                    <td>
                        <%= employee.password %>
                    </td>
                    <td>
                        <%= employee.password_confirm %>
                    </td>
                    <td>
                        <%= link_to  "show  ", employee_path(employee.id) %>
                    </td>
                    <td>
                        <%= link_to  "edit  ", edit_employee_path(employee.id) %>
                    </td>
                    <td>
                        <%= link_to  "delete  ", employee_path(employee.id) %>
                    </td>
                    <td>
                        <%= link_to  "update  ", employee_path(employee.id) %>
                    </td>
                </tr>
                <% end %>
        </tbody>
</table>

app/views/employees/new.html.erb
<h1>New Employee</h1>
<!-- <%= render 'form', employee: @employee %> -->
<%= form_for(@employee) do |f| %>
    <h2>
        <%= @employee.errors.full_messages %>
    </h2>
    Name:
    <Br>
    <%= f.text_field :name %>
        Email:
        <Br>
        <%= f.text_field :email %>
            Passwork:
            <br>
            <%= f.text_field :password %>
                Passwork Confirm:
                <br>
                <%= f.text_field :password_confirm %>
                    <br>
                    <%= f.submit  "Create" %>
                        <% end %>

app/views/employees/show.html.erb
<p id="notice">
    <%= notice %>
</p>
<p><strong>Name: </strong>
    <%= @employee.name %>
        <p>
            <p><strong>Email: </strong>
                <%= @employee.email %>
                    <p>
                        <p><strong>Password: </strong>
                            <%= @employee.password %>
                                <p>
                                    <p><strong>Password Confirm: </strong>
                                        <%= @employee.password_confirm %>
                                            <p>
                                                <%= link_to 'Edit', edit_employee_path(@employee) %>
                                                    <%= link_to 'Back', employees_path %>

app/views/rentals/new.html.erb
<%= form_for(@rental) do |f| %>
    Name:
    <Br>
    <%= f.text_field :name %>
        Size:
        <Br>
        <%= f.text_field :size %>
            Price:
            <br>
            <%= f.text_field :price %>
                Color:
                <br>
                <%= f.text_field :color %>
                    Amount:
                    <br>
                    <%= f.text_field :amount %>
                        <br>
                        <%= f.submit  "Create" %>
                            <% end %>

app/views/rentals/show.html.erb
<p id="notice">
    <%= notice %>
</p>
<p><strong>Name: </strong>
    <%= @rental.name %>
        <p>
            <p><strong>Size: </strong>
                <%= @rental.size %>
                    <p>
                        <p><strong>Price: </strong>
                            <%= @rental.price %>
                                <p>
                                    <p><strong>Color: </strong>
                                        <%= @rental.color %>
                                            <p>
                                                <p><strong>Amount: </strong>
                                                    <%= @rental.amount %>
                                                </p>
                                                <%= link_to 'Back', rentals_path %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1><%= change_name %></h1>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container">

        <form class="well form-horizontal" action=" " method="post"  id="contact_form">
    <fieldset>
    
    <!-- Form Name -->
    <legend>Contact Us Today!</legend>
    
    <!-- Text input-->
    
    <div class="form-group">
      <label class="col-md-4 control-label">First Name</label>  
      <div class="col-md-4 inputGroupContainer">
      <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
      <input  name="first_name" placeholder="First Name" class="form-control"  type="text">
        </div>
      </div>
    </div>
    
    <!-- Text input-->
    
    <div class="form-group">
      <label class="col-md-4 control-label" >Last Name</label> 
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
      <input name="last_name" placeholder="Last Name" class="form-control"  type="text">
        </div>
      </div>
    </div>
    
    <!-- Text input-->
           <div class="form-group">
      <label class="col-md-4 control-label">E-Mail</label>  
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
      <input name="email" placeholder="E-Mail Address" class="form-control"  type="text">
        </div>
      </div>
    </div>
    
    
    <!-- Text input-->
           
    <div class="form-group">
      <label class="col-md-4 control-label">Phone #</label>  
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
      <input name="phone" placeholder="(845)555-1212" class="form-control" type="text">
        </div>
      </div>
    </div>
    
    <!-- Text input-->
          
    <div class="form-group">
      <label class="col-md-4 control-label">Address</label>  
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
      <input name="address" placeholder="Address" class="form-control" type="text">
        </div>
      </div>
    </div>
    
    <!-- Text input-->
     
    <div class="form-group">
      <label class="col-md-4 control-label">City</label>  
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
      <input name="city" placeholder="city" class="form-control"  type="text">
        </div>
      </div>
    </div>
    
    <!-- Select Basic -->
       
    <div class="form-group"> 
      <label class="col-md-4 control-label">State</label>
        <div class="col-md-4 selectContainer">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
        <select name="state" class="form-control selectpicker" >
          <option value=" " >Please select your state</option>
          <option>Alabama</option>
          <option>Alaska</option>
          <option >Arizona</option>
          <option >Arkansas</option>
          <option >California</option>
          <option >Colorado</option>
          <option >Connecticut</option>
          <option >Delaware</option>
          <option >District of Columbia</option>
        </select>
      </div>
    </div>
    </div>
    
    <!-- Text input-->
    
    <div class="form-group">
      <label class="col-md-4 control-label">Zip Code</label>  
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
      <input name="zip" placeholder="Zip Code" class="form-control"  type="text">
        </div>
    </div>
    </div>
    
    <!-- Text input-->
    <div class="form-group">
      <label class="col-md-4 control-label">Website or domain name</label>  
       <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
      <input name="website" placeholder="Website or domain name" class="form-control" type="text">
        </div>
      </div>
    </div>
    
    <!-- radio checks -->
     <div class="form-group">
                            <label class="col-md-4 control-label">Do you have hosting?</label>
                            <div class="col-md-4">
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="hosting" value="yes" /> Yes
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="hosting" value="no" /> No
                                    </label>
                                </div>
                            </div>
                        </div>
    
    <!-- Text area -->
      
    <div class="form-group">
      <label class="col-md-4 control-label">Project Description</label>
        <div class="col-md-4 inputGroupContainer">
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                <textarea class="form-control" name="comment" placeholder="Project Description"></textarea>
      </div>
      </div>
    </div>
    
    <!-- Success message -->
    <div class="alert alert-success" role="alert" id="success_message">Success <i class="glyphicon glyphicon-thumbs-up"></i> Thanks for contacting us, we will get back to you shortly.</div>
    
    <!-- Button -->
    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
        <button type="submit" class="btn btn-warning" >Send <span class="glyphicon glyphicon-send"></span></button>
      </div>
    </div>
    
    </fieldset>
    </form>
    </div>
</div><!-- /.container -->

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1><%= change_name %></h1>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="jumbotron text-center">
        <h1>Company</h1> 
        <p>We specialize in blablabla</p> 
        <form class="form-inline">
          <div class="input-group">
            <input type="email" class="form-control" size="50" placeholder="Email Address" required>
            <div class="input-group-btn">
              <button type="button" class="btn btn-danger">Subscribe</button>
            </div>
          </div>
        </form>
</div>
<div class="container-fluid">
        <h2>About Company Page</h2>
        <h4>Lorem ipsum..</h4> 
        <p>Lorem ipsum..</p>
        <button class="btn btn-default btn-lg">Get in Touch</button>
      </div>
      
      <div class="container-fluid bg-grey">
        <h2>Our Values</h2>
        <h4><strong>MISSION:</strong> Our mission lorem ipsum..</h4> 
        <p><strong>VISION:</strong> Our vision Lorem ipsum..
 </div>
 <div class="container-fluid">
        <div class="row">
          <div class="col-sm-8">
            <h2>About Company Page</h2>
            <h4>Lorem ipsum..</h4> 
            <p>Lorem ipsum..</p>
            <button class="btn btn-default btn-lg">Get in Touch</button>
          </div>
          <div class="col-sm-4">
            <span class="glyphicon glyphicon-signal logo"></span>
          </div>
        </div>
      </div>
      
      <div class="container-fluid bg-grey">
        <div class="row">
          <div class="col-sm-4">
            <span class="glyphicon glyphicon-globe logo"></span> 
          </div>
          <div class="col-sm-8">
            <h2>Our Values</h2>
            <h4><strong>MISSION:</strong> Our mission lorem ipsum..</h4> 
            <p><strong>VISION:</strong> Our vision Lorem ipsum..</p>
          </div>
        </div>
      </div>
      <div class="container-fluid text-center">
            <h2>SERVICES</h2>
            <h4>What we offer</h4>
            <br>
            <div class="row">
              <div class="col-sm-4">
                <span class="glyphicon glyphicon-off"></span>
                <h4>POWER</h4>
                <p>Lorem ipsum dolor sit amet..</p>
              </div>
              <div class="col-sm-4">
                <span class="glyphicon glyphicon-heart"></span>
                <h4>LOVE</h4>
                <p>Lorem ipsum dolor sit amet..</p>
              </div>
              <div class="col-sm-4">
                <span class="glyphicon glyphicon-lock"></span>
                <h4>JOB DONE</h4>
                <p>Lorem ipsum dolor sit amet..</p>
              </div>
              </div>
              <br><br>
            <div class="row">
              <div class="col-sm-4">
                <span class="glyphicon glyphicon-leaf"></span>
                <h4>GREEN</h4>
                <p>Lorem ipsum dolor sit amet..</p>
              </div>
              <div class="col-sm-4">
                <span class="glyphicon glyphicon-certificate"></span>
                <h4>CERTIFIED</h4>
                <p>Lorem ipsum dolor sit amet..</p>
              </div>
              <div class="col-sm-4">
                <span class="glyphicon glyphicon-wrench"></span>
                <h4>HARD WORK</h4>
                <p>Lorem ipsum dolor sit amet..</p>
              </div>
            </div>
          </div>

app/views/static_pages/login.html.erb
<% provide(:title, "Login") %>
<form action="/action_page.php">
  <div class="imgcontainer">
    <img src="https://scontent.fdad2-1.fna.fbcdn.net/v/t1.0-9/1002977_379001882200296_286040681_n.jpg?oh=63dd7f18337706fabf998f59c583e861&oe=5AEA993F" alt="Avatar" class="avatar">
  </div>

  <div class="container">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>
        
    <button type="submit">Login</button>
    <label>
      <input type="checkbox" checked="checked"> Remember me
    </label>
  </div>

  <div class="container" style="background-color:#f1f1f1">
    <button type="button" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#">password?</a></span>
  </div>
</form>

app/views/static_pages/logout.html.erb
<% provide(:title, "Logout") %>

app/views/static_pages/register.html.erb
<% provide(:title, "Register") %>
<form action="/action_page.php" style="border:1px solid #ccc">
    <div class="container">
      <h1>Sign Up</h1>
      <p>Please fill in this form to create an account.</p>
      <hr>
  
      <label><b>Email</b></label>
      <input type="text" placeholder="Enter Email" name="email" required>
  
      <label><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>
  
      <label><b>Repeat Password</b></label>
      <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
      
      <label>
        <input type="checkbox" checked="checked" style="margin-bottom:15px"> Remember me
      </label>
      
      <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>
  
      <div class="clearfix">
        <button type="button" class="cancelbtn">Cancel</button>
        <button type="submit" class="signupbtn">Sign Up</button>
      </div>
    </div>
  </form>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :student_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.address %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>